# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170719_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
