# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170719_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
