# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170720_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(verbose_name='\u7f51\u5740'),
        ),
    ]
